# Generated by Django 6.0.4 on 2026-05-11 13:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
