# Generated by Django 6.0.4 on 2026-05-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_service_user_phone_number_user_role_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
