"""
Django settings for smart_hotel project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import ckeditor

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&my+96c*=vp5k0vaxbp0pxpfz_e5&6)5(cfn&l74v-%q&b(_5p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rooms.apps.RoomsConfig',
    'rest_framework',
    'django_filters',
    # 'ckeditor',
    # 'ckeditor_uploader',
    'drf_yasg',
    'cloudinary',
    'oauth2_provider',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smart_hotel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_hotel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'smarthotel',
        'USER': 'root',
        'PASSWORD': 'abc123',
        'HOST': ''  # mặc định localhost
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'rooms.User'

import pymysql
pymysql.install_as_MySQLdb()

import cloudinary.api
cloudinary.config(
    cloud_name="dgosettle",
    api_key="755285325749422",
    api_secret="-S4Uwmv5_B2ajn9_SrDhdXWh0_c",
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

# CLIENT_ID = Z2VFBztgCuHXJmaTvDae0P5Vio0hfpMTMKkugtSA
# CLIENT_SECRET = bHaIH5deWIjYTnGJbOIuVnlOqy50PjjVHQhvLNF8i8M0Y68Mq4kBTgakv4FMQVME2uVBE6WPr2y0VhjFQ5JRzTlbJi5O57fs3i134pWxKYAW7a3RUWWNMUXOQ8W3Rvf3

CLIENT_ID = 'q0QxIoaHENINPcS4iPs7k4fts0c8v0vN0axY5Qmt'
CLIENT_SECRET = 'Tg4MXjuYDjBSiFFNnnGBK9fIhVehKGzIA4Dy6H7BLuppoPMtcJkAp2BS78PH0tFbLvdYiwZcI8ax9hd729lY86j40injERxi0b3j22rO3SglPzMEEbIpF44mlWSWJdVs'


VNPAY_TMN_CODE = "WCTEJ7O4"
VNPAY_HASH_SECRET = "35NQH0FH8QA5OJNVI8WGAJ8P60RXSEDA"
VNPAY_URL = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"

VNPAY_RETURN_URL = "http://127.0.0.1:8000/payments/vnpay-callback/"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


EMAIL_HOST_USER = 'nguyenvinhloi52@gmail.com'
EMAIL_HOST_PASSWORD = 'drnf qabk zafq gfhp'
DEFAULT_FROM_EMAIL = f"Smart Hotel System <{EMAIL_HOST_USER}>"